# Generated by Django 3.2.5 on 2022-03-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_pengujian', models.CharField(max_length=50)),
                ('nama_pengujian', models.CharField(max_length=205)),
                ('nama_penguji', models.CharField(max_length=200)),
                ('waktu_pengujian', models.CharField(max_length=200)),
                ('durasi_algo_1', models.CharField(max_length=10)),
                ('durasi_algo_2', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tbl_pengujian',
            },
        ),
    ]
